// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb) { return GetRootAsCharacterExcel(_bb, new CharacterExcel()); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb, CharacterExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DevName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDevNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDevNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDevNameArray() { return __p.__vector_as_array<byte>(6); }
  public long CostumeGroupId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool IsPlayable { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FlatDataGlobal.ProductionStep ProductionStep { get { int o = __p.__offset(12); return o != 0 ? (FlatDataGlobal.ProductionStep)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ProductionStep.ToDo; } }
  public bool CollectionVisible { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ReleaseDate { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReleaseDateBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetReleaseDateBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetReleaseDateArray() { return __p.__vector_as_array<byte>(16); }
  public string CollectionVisibleStartDate { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleStartDateBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleStartDateBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetCollectionVisibleStartDateArray() { return __p.__vector_as_array<byte>(18); }
  public string CollectionVisibleEndDate { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleEndDateBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleEndDateBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetCollectionVisibleEndDateArray() { return __p.__vector_as_array<byte>(20); }
  public bool IsPlayableCharacter { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint LocalizeEtcId { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public FlatDataGlobal.Rarity Rarity { get { int o = __p.__offset(26); return o != 0 ? (FlatDataGlobal.Rarity)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.Rarity.N; } }
  public bool IsNPC { get { int o = __p.__offset(28); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FlatDataGlobal.TacticEntityType TacticEntityType { get { int o = __p.__offset(30); return o != 0 ? (FlatDataGlobal.TacticEntityType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.TacticEntityType.None; } }
  public bool CanSurvive { get { int o = __p.__offset(32); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsDummy { get { int o = __p.__offset(34); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int SubPartsCount { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatDataGlobal.TacticRole TacticRole { get { int o = __p.__offset(38); return o != 0 ? (FlatDataGlobal.TacticRole)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.TacticRole.None; } }
  public FlatDataGlobal.WeaponType WeaponType { get { int o = __p.__offset(40); return o != 0 ? (FlatDataGlobal.WeaponType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.WeaponType.None; } }
  public FlatDataGlobal.TacticRange TacticRange { get { int o = __p.__offset(42); return o != 0 ? (FlatDataGlobal.TacticRange)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.TacticRange.Back; } }
  public FlatDataGlobal.BulletType BulletType { get { int o = __p.__offset(44); return o != 0 ? (FlatDataGlobal.BulletType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.BulletType.Normal; } }
  public FlatDataGlobal.ArmorType ArmorType { get { int o = __p.__offset(46); return o != 0 ? (FlatDataGlobal.ArmorType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ArmorType.LightArmor; } }
  public FlatDataGlobal.AimIKType AimIKType { get { int o = __p.__offset(48); return o != 0 ? (FlatDataGlobal.AimIKType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.AimIKType.None; } }
  public FlatDataGlobal.School School { get { int o = __p.__offset(50); return o != 0 ? (FlatDataGlobal.School)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.School.None; } }
  public FlatDataGlobal.Club Club { get { int o = __p.__offset(52); return o != 0 ? (FlatDataGlobal.Club)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.Club.None; } }
  public int DefaultStarGrade { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxStarGrade { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatDataGlobal.StatLevelUpType StatLevelUpType { get { int o = __p.__offset(58); return o != 0 ? (FlatDataGlobal.StatLevelUpType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.StatLevelUpType.Standard; } }
  public FlatDataGlobal.SquadType SquadType { get { int o = __p.__offset(60); return o != 0 ? (FlatDataGlobal.SquadType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.SquadType.None; } }
  public bool Jumpable { get { int o = __p.__offset(62); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long PersonalityId { get { int o = __p.__offset(64); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CharacterAIId { get { int o = __p.__offset(66); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ExternalBTId { get { int o = __p.__offset(68); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string ScenarioCharacter { get { int o = __p.__offset(70); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetScenarioCharacterBytes() { return __p.__vector_as_span<byte>(70, 1); }
#else
  public ArraySegment<byte>? GetScenarioCharacterBytes() { return __p.__vector_as_arraysegment(70); }
#endif
  public byte[] GetScenarioCharacterArray() { return __p.__vector_as_array<byte>(70); }
  public uint SpawnTemplateId { get { int o = __p.__offset(72); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int FavorLevelupType { get { int o = __p.__offset(74); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatDataGlobal.EquipmentCategory EquipmentSlot(int j) { int o = __p.__offset(76); return o != 0 ? (FlatDataGlobal.EquipmentCategory)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatDataGlobal.EquipmentCategory)0; }
  public int EquipmentSlotLength { get { int o = __p.__offset(76); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatDataGlobal.EquipmentCategory> GetEquipmentSlotBytes() { return __p.__vector_as_span<FlatDataGlobal.EquipmentCategory>(76, 4); }
#else
  public ArraySegment<byte>? GetEquipmentSlotBytes() { return __p.__vector_as_arraysegment(76); }
#endif
  public FlatDataGlobal.EquipmentCategory[] GetEquipmentSlotArray() { int o = __p.__offset(76); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatDataGlobal.EquipmentCategory[] a = new FlatDataGlobal.EquipmentCategory[l]; for (int i = 0; i < l; i++) { a[i] = (FlatDataGlobal.EquipmentCategory)__p.bb.GetInt(p + i * 4); } return a; }
  public uint WeaponLocalizeId { get { int o = __p.__offset(78); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool DisplayEnemyInfo { get { int o = __p.__offset(80); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long BodyRadius { get { int o = __p.__offset(82); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RandomEffectRadius { get { int o = __p.__offset(84); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool HPBarHide { get { int o = __p.__offset(86); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float HpBarHeight { get { int o = __p.__offset(88); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HighlightFloaterHeight { get { int o = __p.__offset(90); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetX { get { int o = __p.__offset(92); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetY { get { int o = __p.__offset(94); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int MoveStartFrame { get { int o = __p.__offset(96); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MoveEndFrame { get { int o = __p.__offset(98); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int JumpMotionFrame { get { int o = __p.__offset(100); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AppearFrame { get { int o = __p.__offset(102); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool CanMove { get { int o = __p.__offset(104); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanFix { get { int o = __p.__offset(106); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanCrowdControl { get { int o = __p.__offset(108); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanBattleItemMove { get { int o = __p.__offset(110); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsAirUnit { get { int o = __p.__offset(112); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long AirUnitHeight { get { int o = __p.__offset(114); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatDataGlobal.Tag Tags(int j) { int o = __p.__offset(116); return o != 0 ? (FlatDataGlobal.Tag)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatDataGlobal.Tag)0; }
  public int TagsLength { get { int o = __p.__offset(116); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatDataGlobal.Tag> GetTagsBytes() { return __p.__vector_as_span<FlatDataGlobal.Tag>(116, 4); }
#else
  public ArraySegment<byte>? GetTagsBytes() { return __p.__vector_as_arraysegment(116); }
#endif
  public FlatDataGlobal.Tag[] GetTagsArray() { int o = __p.__offset(116); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatDataGlobal.Tag[] a = new FlatDataGlobal.Tag[l]; for (int i = 0; i < l; i++) { a[i] = (FlatDataGlobal.Tag)__p.bb.GetInt(p + i * 4); } return a; }
  public long SecretStoneItemId { get { int o = __p.__offset(118); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int SecretStoneItemAmount { get { int o = __p.__offset(120); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CharacterPieceItemId { get { int o = __p.__offset(122); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CharacterPieceItemAmount { get { int o = __p.__offset(124); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CombineRecipeId { get { int o = __p.__offset(126); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatDataGlobal.CharacterExcel> CreateCharacterExcel(FlatBufferBuilder builder,
      long Id = 0,
      StringOffset DevNameOffset = default(StringOffset),
      long CostumeGroupId = 0,
      bool IsPlayable = false,
      FlatDataGlobal.ProductionStep productionStep = FlatDataGlobal.ProductionStep.ToDo,
      bool CollectionVisible = false,
      StringOffset ReleaseDateOffset = default(StringOffset),
      StringOffset CollectionVisibleStartDateOffset = default(StringOffset),
      StringOffset CollectionVisibleEndDateOffset = default(StringOffset),
      bool IsPlayableCharacter = false,
      uint LocalizeEtcId = 0,
      FlatDataGlobal.Rarity rarity = FlatDataGlobal.Rarity.N,
      bool IsNPC = false,
      FlatDataGlobal.TacticEntityType tacticEntityType = FlatDataGlobal.TacticEntityType.None,
      bool CanSurvive = false,
      bool IsDummy = false,
      int SubPartsCount = 0,
      FlatDataGlobal.TacticRole tacticRole = FlatDataGlobal.TacticRole.None,
      FlatDataGlobal.WeaponType weaponType = FlatDataGlobal.WeaponType.None,
      FlatDataGlobal.TacticRange tacticRange = FlatDataGlobal.TacticRange.Back,
      FlatDataGlobal.BulletType bulletType = FlatDataGlobal.BulletType.Normal,
      FlatDataGlobal.ArmorType armorType = FlatDataGlobal.ArmorType.LightArmor,
      FlatDataGlobal.AimIKType aimIKType = FlatDataGlobal.AimIKType.None,
      FlatDataGlobal.School school = FlatDataGlobal.School.None,
      FlatDataGlobal.Club club = FlatDataGlobal.Club.None,
      int DefaultStarGrade = 0,
      int MaxStarGrade = 0,
      FlatDataGlobal.StatLevelUpType statLevelUpType = FlatDataGlobal.StatLevelUpType.Standard,
      FlatDataGlobal.SquadType squadType = FlatDataGlobal.SquadType.None,
      bool Jumpable = false,
      long PersonalityId = 0,
      long CharacterAIId = 0,
      long ExternalBTId = 0,
      StringOffset ScenarioCharacterOffset = default(StringOffset),
      uint SpawnTemplateId = 0,
      int FavorLevelupType = 0,
      VectorOffset EquipmentSlotOffset = default(VectorOffset),
      uint WeaponLocalizeId = 0,
      bool DisplayEnemyInfo = false,
      long BodyRadius = 0,
      long RandomEffectRadius = 0,
      bool HPBarHide = false,
      float HpBarHeight = 0.0f,
      float HighlightFloaterHeight = 0.0f,
      float EmojiOffsetX = 0.0f,
      float EmojiOffsetY = 0.0f,
      int MoveStartFrame = 0,
      int MoveEndFrame = 0,
      int JumpMotionFrame = 0,
      int AppearFrame = 0,
      bool CanMove = false,
      bool CanFix = false,
      bool CanCrowdControl = false,
      bool CanBattleItemMove = false,
      bool IsAirUnit = false,
      long AirUnitHeight = 0,
      VectorOffset TagsOffset = default(VectorOffset),
      long SecretStoneItemId = 0,
      int SecretStoneItemAmount = 0,
      long CharacterPieceItemId = 0,
      int CharacterPieceItemAmount = 0,
      long CombineRecipeId = 0) {
    builder.StartTable(62);
    CharacterExcel.AddCombineRecipeId(builder, CombineRecipeId);
    CharacterExcel.AddCharacterPieceItemId(builder, CharacterPieceItemId);
    CharacterExcel.AddSecretStoneItemId(builder, SecretStoneItemId);
    CharacterExcel.AddAirUnitHeight(builder, AirUnitHeight);
    CharacterExcel.AddRandomEffectRadius(builder, RandomEffectRadius);
    CharacterExcel.AddBodyRadius(builder, BodyRadius);
    CharacterExcel.AddExternalBTId(builder, ExternalBTId);
    CharacterExcel.AddCharacterAIId(builder, CharacterAIId);
    CharacterExcel.AddPersonalityId(builder, PersonalityId);
    CharacterExcel.AddCostumeGroupId(builder, CostumeGroupId);
    CharacterExcel.AddId(builder, Id);
    CharacterExcel.AddCharacterPieceItemAmount(builder, CharacterPieceItemAmount);
    CharacterExcel.AddSecretStoneItemAmount(builder, SecretStoneItemAmount);
    CharacterExcel.AddTags(builder, TagsOffset);
    CharacterExcel.AddAppearFrame(builder, AppearFrame);
    CharacterExcel.AddJumpMotionFrame(builder, JumpMotionFrame);
    CharacterExcel.AddMoveEndFrame(builder, MoveEndFrame);
    CharacterExcel.AddMoveStartFrame(builder, MoveStartFrame);
    CharacterExcel.AddEmojiOffsetY(builder, EmojiOffsetY);
    CharacterExcel.AddEmojiOffsetX(builder, EmojiOffsetX);
    CharacterExcel.AddHighlightFloaterHeight(builder, HighlightFloaterHeight);
    CharacterExcel.AddHpBarHeight(builder, HpBarHeight);
    CharacterExcel.AddWeaponLocalizeId(builder, WeaponLocalizeId);
    CharacterExcel.AddEquipmentSlot(builder, EquipmentSlotOffset);
    CharacterExcel.AddFavorLevelupType(builder, FavorLevelupType);
    CharacterExcel.AddSpawnTemplateId(builder, SpawnTemplateId);
    CharacterExcel.AddScenarioCharacter(builder, ScenarioCharacterOffset);
    CharacterExcel.AddSquadType(builder, squadType);
    CharacterExcel.AddStatLevelUpType(builder, statLevelUpType);
    CharacterExcel.AddMaxStarGrade(builder, MaxStarGrade);
    CharacterExcel.AddDefaultStarGrade(builder, DefaultStarGrade);
    CharacterExcel.AddClub(builder, club);
    CharacterExcel.AddSchool(builder, school);
    CharacterExcel.AddAimIKType(builder, aimIKType);
    CharacterExcel.AddArmorType(builder, armorType);
    CharacterExcel.AddBulletType(builder, bulletType);
    CharacterExcel.AddTacticRange(builder, tacticRange);
    CharacterExcel.AddWeaponType(builder, weaponType);
    CharacterExcel.AddTacticRole(builder, tacticRole);
    CharacterExcel.AddSubPartsCount(builder, SubPartsCount);
    CharacterExcel.AddTacticEntityType(builder, tacticEntityType);
    CharacterExcel.AddRarity(builder, rarity);
    CharacterExcel.AddLocalizeEtcId(builder, LocalizeEtcId);
    CharacterExcel.AddCollectionVisibleEndDate(builder, CollectionVisibleEndDateOffset);
    CharacterExcel.AddCollectionVisibleStartDate(builder, CollectionVisibleStartDateOffset);
    CharacterExcel.AddReleaseDate(builder, ReleaseDateOffset);
    CharacterExcel.AddProductionStep(builder, productionStep);
    CharacterExcel.AddDevName(builder, DevNameOffset);
    CharacterExcel.AddIsAirUnit(builder, IsAirUnit);
    CharacterExcel.AddCanBattleItemMove(builder, CanBattleItemMove);
    CharacterExcel.AddCanCrowdControl(builder, CanCrowdControl);
    CharacterExcel.AddCanFix(builder, CanFix);
    CharacterExcel.AddCanMove(builder, CanMove);
    CharacterExcel.AddHPBarHide(builder, HPBarHide);
    CharacterExcel.AddDisplayEnemyInfo(builder, DisplayEnemyInfo);
    CharacterExcel.AddJumpable(builder, Jumpable);
    CharacterExcel.AddIsDummy(builder, IsDummy);
    CharacterExcel.AddCanSurvive(builder, CanSurvive);
    CharacterExcel.AddIsNPC(builder, IsNPC);
    CharacterExcel.AddIsPlayableCharacter(builder, IsPlayableCharacter);
    CharacterExcel.AddCollectionVisible(builder, CollectionVisible);
    CharacterExcel.AddIsPlayable(builder, IsPlayable);
    return CharacterExcel.EndCharacterExcel(builder);
  }

  public static void StartCharacterExcel(FlatBufferBuilder builder) { builder.StartTable(62); }
  public static void AddId(FlatBufferBuilder builder, long Id) { builder.AddLong(0, Id, 0); }
  public static void AddDevName(FlatBufferBuilder builder, StringOffset DevNameOffset) { builder.AddOffset(1, DevNameOffset.Value, 0); }
  public static void AddCostumeGroupId(FlatBufferBuilder builder, long CostumeGroupId) { builder.AddLong(2, CostumeGroupId, 0); }
  public static void AddIsPlayable(FlatBufferBuilder builder, bool IsPlayable) { builder.AddBool(3, IsPlayable, false); }
  public static void AddProductionStep(FlatBufferBuilder builder, FlatDataGlobal.ProductionStep productionStep) { builder.AddInt(4, (int)productionStep, 0); }
  public static void AddCollectionVisible(FlatBufferBuilder builder, bool CollectionVisible) { builder.AddBool(5, CollectionVisible, false); }
  public static void AddReleaseDate(FlatBufferBuilder builder, StringOffset ReleaseDateOffset) { builder.AddOffset(6, ReleaseDateOffset.Value, 0); }
  public static void AddCollectionVisibleStartDate(FlatBufferBuilder builder, StringOffset CollectionVisibleStartDateOffset) { builder.AddOffset(7, CollectionVisibleStartDateOffset.Value, 0); }
  public static void AddCollectionVisibleEndDate(FlatBufferBuilder builder, StringOffset CollectionVisibleEndDateOffset) { builder.AddOffset(8, CollectionVisibleEndDateOffset.Value, 0); }
  public static void AddIsPlayableCharacter(FlatBufferBuilder builder, bool IsPlayableCharacter) { builder.AddBool(9, IsPlayableCharacter, false); }
  public static void AddLocalizeEtcId(FlatBufferBuilder builder, uint LocalizeEtcId) { builder.AddUint(10, LocalizeEtcId, 0); }
  public static void AddRarity(FlatBufferBuilder builder, FlatDataGlobal.Rarity rarity) { builder.AddInt(11, (int)rarity, 0); }
  public static void AddIsNPC(FlatBufferBuilder builder, bool IsNPC) { builder.AddBool(12, IsNPC, false); }
  public static void AddTacticEntityType(FlatBufferBuilder builder, FlatDataGlobal.TacticEntityType tacticEntityType) { builder.AddInt(13, (int)tacticEntityType, 0); }
  public static void AddCanSurvive(FlatBufferBuilder builder, bool CanSurvive) { builder.AddBool(14, CanSurvive, false); }
  public static void AddIsDummy(FlatBufferBuilder builder, bool IsDummy) { builder.AddBool(15, IsDummy, false); }
  public static void AddSubPartsCount(FlatBufferBuilder builder, int SubPartsCount) { builder.AddInt(16, SubPartsCount, 0); }
  public static void AddTacticRole(FlatBufferBuilder builder, FlatDataGlobal.TacticRole tacticRole) { builder.AddInt(17, (int)tacticRole, 0); }
  public static void AddWeaponType(FlatBufferBuilder builder, FlatDataGlobal.WeaponType weaponType) { builder.AddInt(18, (int)weaponType, 0); }
  public static void AddTacticRange(FlatBufferBuilder builder, FlatDataGlobal.TacticRange tacticRange) { builder.AddInt(19, (int)tacticRange, 0); }
  public static void AddBulletType(FlatBufferBuilder builder, FlatDataGlobal.BulletType bulletType) { builder.AddInt(20, (int)bulletType, 0); }
  public static void AddArmorType(FlatBufferBuilder builder, FlatDataGlobal.ArmorType armorType) { builder.AddInt(21, (int)armorType, 0); }
  public static void AddAimIKType(FlatBufferBuilder builder, FlatDataGlobal.AimIKType aimIKType) { builder.AddInt(22, (int)aimIKType, 0); }
  public static void AddSchool(FlatBufferBuilder builder, FlatDataGlobal.School school) { builder.AddInt(23, (int)school, 0); }
  public static void AddClub(FlatBufferBuilder builder, FlatDataGlobal.Club club) { builder.AddInt(24, (int)club, 0); }
  public static void AddDefaultStarGrade(FlatBufferBuilder builder, int DefaultStarGrade) { builder.AddInt(25, DefaultStarGrade, 0); }
  public static void AddMaxStarGrade(FlatBufferBuilder builder, int MaxStarGrade) { builder.AddInt(26, MaxStarGrade, 0); }
  public static void AddStatLevelUpType(FlatBufferBuilder builder, FlatDataGlobal.StatLevelUpType statLevelUpType) { builder.AddInt(27, (int)statLevelUpType, 0); }
  public static void AddSquadType(FlatBufferBuilder builder, FlatDataGlobal.SquadType squadType) { builder.AddInt(28, (int)squadType, 0); }
  public static void AddJumpable(FlatBufferBuilder builder, bool Jumpable) { builder.AddBool(29, Jumpable, false); }
  public static void AddPersonalityId(FlatBufferBuilder builder, long PersonalityId) { builder.AddLong(30, PersonalityId, 0); }
  public static void AddCharacterAIId(FlatBufferBuilder builder, long CharacterAIId) { builder.AddLong(31, CharacterAIId, 0); }
  public static void AddExternalBTId(FlatBufferBuilder builder, long ExternalBTId) { builder.AddLong(32, ExternalBTId, 0); }
  public static void AddScenarioCharacter(FlatBufferBuilder builder, StringOffset ScenarioCharacterOffset) { builder.AddOffset(33, ScenarioCharacterOffset.Value, 0); }
  public static void AddSpawnTemplateId(FlatBufferBuilder builder, uint SpawnTemplateId) { builder.AddUint(34, SpawnTemplateId, 0); }
  public static void AddFavorLevelupType(FlatBufferBuilder builder, int FavorLevelupType) { builder.AddInt(35, FavorLevelupType, 0); }
  public static void AddEquipmentSlot(FlatBufferBuilder builder, VectorOffset EquipmentSlotOffset) { builder.AddOffset(36, EquipmentSlotOffset.Value, 0); }
  public static VectorOffset CreateEquipmentSlotVector(FlatBufferBuilder builder, FlatDataGlobal.EquipmentCategory[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, FlatDataGlobal.EquipmentCategory[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatDataGlobal.EquipmentCategory> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatDataGlobal.EquipmentCategory>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipmentSlotVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWeaponLocalizeId(FlatBufferBuilder builder, uint WeaponLocalizeId) { builder.AddUint(37, WeaponLocalizeId, 0); }
  public static void AddDisplayEnemyInfo(FlatBufferBuilder builder, bool DisplayEnemyInfo) { builder.AddBool(38, DisplayEnemyInfo, false); }
  public static void AddBodyRadius(FlatBufferBuilder builder, long BodyRadius) { builder.AddLong(39, BodyRadius, 0); }
  public static void AddRandomEffectRadius(FlatBufferBuilder builder, long RandomEffectRadius) { builder.AddLong(40, RandomEffectRadius, 0); }
  public static void AddHPBarHide(FlatBufferBuilder builder, bool HPBarHide) { builder.AddBool(41, HPBarHide, false); }
  public static void AddHpBarHeight(FlatBufferBuilder builder, float HpBarHeight) { builder.AddFloat(42, HpBarHeight, 0.0f); }
  public static void AddHighlightFloaterHeight(FlatBufferBuilder builder, float HighlightFloaterHeight) { builder.AddFloat(43, HighlightFloaterHeight, 0.0f); }
  public static void AddEmojiOffsetX(FlatBufferBuilder builder, float EmojiOffsetX) { builder.AddFloat(44, EmojiOffsetX, 0.0f); }
  public static void AddEmojiOffsetY(FlatBufferBuilder builder, float EmojiOffsetY) { builder.AddFloat(45, EmojiOffsetY, 0.0f); }
  public static void AddMoveStartFrame(FlatBufferBuilder builder, int MoveStartFrame) { builder.AddInt(46, MoveStartFrame, 0); }
  public static void AddMoveEndFrame(FlatBufferBuilder builder, int MoveEndFrame) { builder.AddInt(47, MoveEndFrame, 0); }
  public static void AddJumpMotionFrame(FlatBufferBuilder builder, int JumpMotionFrame) { builder.AddInt(48, JumpMotionFrame, 0); }
  public static void AddAppearFrame(FlatBufferBuilder builder, int AppearFrame) { builder.AddInt(49, AppearFrame, 0); }
  public static void AddCanMove(FlatBufferBuilder builder, bool CanMove) { builder.AddBool(50, CanMove, false); }
  public static void AddCanFix(FlatBufferBuilder builder, bool CanFix) { builder.AddBool(51, CanFix, false); }
  public static void AddCanCrowdControl(FlatBufferBuilder builder, bool CanCrowdControl) { builder.AddBool(52, CanCrowdControl, false); }
  public static void AddCanBattleItemMove(FlatBufferBuilder builder, bool CanBattleItemMove) { builder.AddBool(53, CanBattleItemMove, false); }
  public static void AddIsAirUnit(FlatBufferBuilder builder, bool IsAirUnit) { builder.AddBool(54, IsAirUnit, false); }
  public static void AddAirUnitHeight(FlatBufferBuilder builder, long AirUnitHeight) { builder.AddLong(55, AirUnitHeight, 0); }
  public static void AddTags(FlatBufferBuilder builder, VectorOffset TagsOffset) { builder.AddOffset(56, TagsOffset.Value, 0); }
  public static VectorOffset CreateTagsVector(FlatBufferBuilder builder, FlatDataGlobal.Tag[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, FlatDataGlobal.Tag[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatDataGlobal.Tag> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatDataGlobal.Tag>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTagsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSecretStoneItemId(FlatBufferBuilder builder, long SecretStoneItemId) { builder.AddLong(57, SecretStoneItemId, 0); }
  public static void AddSecretStoneItemAmount(FlatBufferBuilder builder, int SecretStoneItemAmount) { builder.AddInt(58, SecretStoneItemAmount, 0); }
  public static void AddCharacterPieceItemId(FlatBufferBuilder builder, long CharacterPieceItemId) { builder.AddLong(59, CharacterPieceItemId, 0); }
  public static void AddCharacterPieceItemAmount(FlatBufferBuilder builder, int CharacterPieceItemAmount) { builder.AddInt(60, CharacterPieceItemAmount, 0); }
  public static void AddCombineRecipeId(FlatBufferBuilder builder, long CombineRecipeId) { builder.AddLong(61, CombineRecipeId, 0); }
  public static Offset<FlatDataGlobal.CharacterExcel> EndCharacterExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataGlobal.CharacterExcel>(o);
  }
}


}
