// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum CharacterVoiceOverridePriority : int
{
  None = 0,
  High = 1,
  Low = 2,
};


}
