// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum ConcentrationVoiceCondition : int
{
  None = 0,
  PairMatchFail = 1,
  PairMatchSuccess = 2,
  RoundRenewal = 3,
};


}
