// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum ContentType : int
{
  None = 0,
  CampaignMainStage = 1,
  CampaignSubStage = 2,
  WeekDungeon = 3,
  EventContentMainStage = 4,
  EventContentSubStage = 5,
  CampaignTutorialStage = 6,
  EventContentMainGroundStage = 7,
  SchoolDungeon = 8,
  TimeAttackDungeon = 9,
  Raid = 10,
  Conquest = 11,
  EventContentStoryStage = 12,
  CampaignExtraStage = 13,
  StoryStrategyStage = 14,
};


}
