// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum EventChangeType : int
{
  MainSub = 0,
  SubMain = 1,
};


}
