// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventContentConcentrationExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static EventContentConcentrationExcel GetRootAsEventContentConcentrationExcel(ByteBuffer _bb) { return GetRootAsEventContentConcentrationExcel(_bb, new EventContentConcentrationExcel()); }
  public static EventContentConcentrationExcel GetRootAsEventContentConcentrationExcel(ByteBuffer _bb, EventContentConcentrationExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EventContentConcentrationExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long EventContentId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CostGoodsId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int MaxCardPairCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxCardOpenCount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int InstantClearRound { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string CardBoardPrefabs { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCardBoardPrefabsBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetCardBoardPrefabsBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetCardBoardPrefabsArray() { return __p.__vector_as_array<byte>(14); }
  public string BackImagePath { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBackImagePathBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetBackImagePathBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetBackImagePathArray() { return __p.__vector_as_array<byte>(16); }

  public static Offset<FlatDataGlobal.EventContentConcentrationExcel> CreateEventContentConcentrationExcel(FlatBufferBuilder builder,
      long EventContentId = 0,
      long CostGoodsId = 0,
      int MaxCardPairCount = 0,
      int MaxCardOpenCount = 0,
      int InstantClearRound = 0,
      StringOffset CardBoardPrefabsOffset = default(StringOffset),
      StringOffset BackImagePathOffset = default(StringOffset)) {
    builder.StartTable(7);
    EventContentConcentrationExcel.AddCostGoodsId(builder, CostGoodsId);
    EventContentConcentrationExcel.AddEventContentId(builder, EventContentId);
    EventContentConcentrationExcel.AddBackImagePath(builder, BackImagePathOffset);
    EventContentConcentrationExcel.AddCardBoardPrefabs(builder, CardBoardPrefabsOffset);
    EventContentConcentrationExcel.AddInstantClearRound(builder, InstantClearRound);
    EventContentConcentrationExcel.AddMaxCardOpenCount(builder, MaxCardOpenCount);
    EventContentConcentrationExcel.AddMaxCardPairCount(builder, MaxCardPairCount);
    return EventContentConcentrationExcel.EndEventContentConcentrationExcel(builder);
  }

  public static void StartEventContentConcentrationExcel(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddEventContentId(FlatBufferBuilder builder, long EventContentId) { builder.AddLong(0, EventContentId, 0); }
  public static void AddCostGoodsId(FlatBufferBuilder builder, long CostGoodsId) { builder.AddLong(1, CostGoodsId, 0); }
  public static void AddMaxCardPairCount(FlatBufferBuilder builder, int MaxCardPairCount) { builder.AddInt(2, MaxCardPairCount, 0); }
  public static void AddMaxCardOpenCount(FlatBufferBuilder builder, int MaxCardOpenCount) { builder.AddInt(3, MaxCardOpenCount, 0); }
  public static void AddInstantClearRound(FlatBufferBuilder builder, int InstantClearRound) { builder.AddInt(4, InstantClearRound, 0); }
  public static void AddCardBoardPrefabs(FlatBufferBuilder builder, StringOffset CardBoardPrefabsOffset) { builder.AddOffset(5, CardBoardPrefabsOffset.Value, 0); }
  public static void AddBackImagePath(FlatBufferBuilder builder, StringOffset BackImagePathOffset) { builder.AddOffset(6, BackImagePathOffset.Value, 0); }
  public static Offset<FlatDataGlobal.EventContentConcentrationExcel> EndEventContentConcentrationExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataGlobal.EventContentConcentrationExcel>(o);
  }
}


}
