// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum GachaGroupType : int
{
  None = 0,
  Reward_General = 1,
  System_Craft = 2,
  Reward_Pack = 3,
};


}
