// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MinigameCCGStartDeckCardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static MinigameCCGStartDeckCardExcel GetRootAsMinigameCCGStartDeckCardExcel(ByteBuffer _bb) { return GetRootAsMinigameCCGStartDeckCardExcel(_bb, new MinigameCCGStartDeckCardExcel()); }
  public static MinigameCCGStartDeckCardExcel GetRootAsMinigameCCGStartDeckCardExcel(ByteBuffer _bb, MinigameCCGStartDeckCardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MinigameCCGStartDeckCardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long CCGId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CardId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatDataGlobal.MinigameCCGStartDeckCardExcel> CreateMinigameCCGStartDeckCardExcel(FlatBufferBuilder builder,
      long CCGId = 0,
      long CardId = 0) {
    builder.StartTable(2);
    MinigameCCGStartDeckCardExcel.AddCardId(builder, CardId);
    MinigameCCGStartDeckCardExcel.AddCCGId(builder, CCGId);
    return MinigameCCGStartDeckCardExcel.EndMinigameCCGStartDeckCardExcel(builder);
  }

  public static void StartMinigameCCGStartDeckCardExcel(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCCGId(FlatBufferBuilder builder, long CCGId) { builder.AddLong(0, CCGId, 0); }
  public static void AddCardId(FlatBufferBuilder builder, long CardId) { builder.AddLong(1, CardId, 0); }
  public static Offset<FlatDataGlobal.MinigameCCGStartDeckCardExcel> EndMinigameCCGStartDeckCardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataGlobal.MinigameCCGStartDeckCardExcel>(o);
  }
}


}
