// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum MiniGameTBGThemaRewardType : int
{
  TreasureReward = 0,
  EmptyTreasureReward = 1,
};


}
