// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum ObstacleCoverType : int
{
  None = 0,
  Cover = 1,
  Shelter = 2,
};


}
