// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PossessionCheckExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PossessionCheckExcel GetRootAsPossessionCheckExcel(ByteBuffer _bb) { return GetRootAsPossessionCheckExcel(_bb, new PossessionCheckExcel()); }
  public static PossessionCheckExcel GetRootAsPossessionCheckExcel(ByteBuffer _bb, PossessionCheckExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PossessionCheckExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UniqueId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatDataGlobal.ParcelType DefaultParcelType { get { int o = __p.__offset(6); return o != 0 ? (FlatDataGlobal.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ParcelType.None; } }
  public long DefaultParcelId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int DefaultParcelAmount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatDataGlobal.ParcelType ReplaceParcelType { get { int o = __p.__offset(12); return o != 0 ? (FlatDataGlobal.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ParcelType.None; } }
  public long ReplaceParcelId { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int ReplaceParcelAmount { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatDataGlobal.PossessionCheckExcel> CreatePossessionCheckExcel(FlatBufferBuilder builder,
      long UniqueId = 0,
      FlatDataGlobal.ParcelType DefaultParcelType = FlatDataGlobal.ParcelType.None,
      long DefaultParcelId = 0,
      int DefaultParcelAmount = 0,
      FlatDataGlobal.ParcelType ReplaceParcelType = FlatDataGlobal.ParcelType.None,
      long ReplaceParcelId = 0,
      int ReplaceParcelAmount = 0) {
    builder.StartTable(7);
    PossessionCheckExcel.AddReplaceParcelId(builder, ReplaceParcelId);
    PossessionCheckExcel.AddDefaultParcelId(builder, DefaultParcelId);
    PossessionCheckExcel.AddUniqueId(builder, UniqueId);
    PossessionCheckExcel.AddReplaceParcelAmount(builder, ReplaceParcelAmount);
    PossessionCheckExcel.AddReplaceParcelType(builder, ReplaceParcelType);
    PossessionCheckExcel.AddDefaultParcelAmount(builder, DefaultParcelAmount);
    PossessionCheckExcel.AddDefaultParcelType(builder, DefaultParcelType);
    return PossessionCheckExcel.EndPossessionCheckExcel(builder);
  }

  public static void StartPossessionCheckExcel(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddUniqueId(FlatBufferBuilder builder, long UniqueId) { builder.AddLong(0, UniqueId, 0); }
  public static void AddDefaultParcelType(FlatBufferBuilder builder, FlatDataGlobal.ParcelType DefaultParcelType) { builder.AddInt(1, (int)DefaultParcelType, 0); }
  public static void AddDefaultParcelId(FlatBufferBuilder builder, long DefaultParcelId) { builder.AddLong(2, DefaultParcelId, 0); }
  public static void AddDefaultParcelAmount(FlatBufferBuilder builder, int DefaultParcelAmount) { builder.AddInt(3, DefaultParcelAmount, 0); }
  public static void AddReplaceParcelType(FlatBufferBuilder builder, FlatDataGlobal.ParcelType ReplaceParcelType) { builder.AddInt(4, (int)ReplaceParcelType, 0); }
  public static void AddReplaceParcelId(FlatBufferBuilder builder, long ReplaceParcelId) { builder.AddLong(5, ReplaceParcelId, 0); }
  public static void AddReplaceParcelAmount(FlatBufferBuilder builder, int ReplaceParcelAmount) { builder.AddInt(6, ReplaceParcelAmount, 0); }
  public static Offset<FlatDataGlobal.PossessionCheckExcel> EndPossessionCheckExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataGlobal.PossessionCheckExcel>(o);
  }
}


}
