// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ShopRecruitExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ShopRecruitExcel GetRootAsShopRecruitExcel(ByteBuffer _bb) { return GetRootAsShopRecruitExcel(_bb, new ShopRecruitExcel()); }
  public static ShopRecruitExcel GetRootAsShopRecruitExcel(ByteBuffer _bb, ShopRecruitExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShopRecruitExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatDataGlobal.ShopCategoryType CategoryType { get { int o = __p.__offset(6); return o != 0 ? (FlatDataGlobal.ShopCategoryType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ShopCategoryType.General; } }
  public bool IsLegacy { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long OneGachaGoodsId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long TenGachaGoodsId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string GoodsDevName { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGoodsDevNameBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetGoodsDevNameBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetGoodsDevNameArray() { return __p.__vector_as_array<byte>(14); }
  public FlatDataGlobal.GachaDisplayTag DisplayTag { get { int o = __p.__offset(16); return o != 0 ? (FlatDataGlobal.GachaDisplayTag)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.GachaDisplayTag.None; } }
  public long DisplayOrder { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string GachaBannerPath { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaBannerPathBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetGachaBannerPathBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetGachaBannerPathArray() { return __p.__vector_as_array<byte>(20); }
  public string MovieBannerPath(int j) { int o = __p.__offset(22); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int MovieBannerPathLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string MovieBannerPathTeen(int j) { int o = __p.__offset(24); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int MovieBannerPathTeenLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
  public long LinkedRobbyBannerId { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long InfoCharacterId(int j) { int o = __p.__offset(28); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int InfoCharacterIdLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetInfoCharacterIdBytes() { return __p.__vector_as_span<long>(28, 8); }
#else
  public ArraySegment<byte>? GetInfoCharacterIdBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public long[] GetInfoCharacterIdArray() { return __p.__vector_as_array<long>(28); }
  public string SalePeriodFrom { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSalePeriodFromBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetSalePeriodFromBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetSalePeriodFromArray() { return __p.__vector_as_array<byte>(30); }
  public string SalePeriodTo { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSalePeriodToBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetSalePeriodToBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetSalePeriodToArray() { return __p.__vector_as_array<byte>(32); }
  public long RecruitCoinId { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RecruitSellectionShopId { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PurchaseCooltimeMin { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PurchaseCountLimit { get { int o = __p.__offset(40); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatDataGlobal.PurchaseCountResetType PurchaseCountResetType { get { int o = __p.__offset(42); return o != 0 ? (FlatDataGlobal.PurchaseCountResetType)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.PurchaseCountResetType.None; } }
  public bool IsNewbie { get { int o = __p.__offset(44); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsSelectRecruit { get { int o = __p.__offset(46); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long DirectPayInvisibleTokenId { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DirectPayAndroidShopCashId { get { int o = __p.__offset(50); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DirectPayAppleShopCashId { get { int o = __p.__offset(52); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DirectPayOneStoreShopCashId { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string ProbabilityUrlDev { get { int o = __p.__offset(56); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProbabilityUrlDevBytes() { return __p.__vector_as_span<byte>(56, 1); }
#else
  public ArraySegment<byte>? GetProbabilityUrlDevBytes() { return __p.__vector_as_arraysegment(56); }
#endif
  public byte[] GetProbabilityUrlDevArray() { return __p.__vector_as_array<byte>(56); }
  public string ProbabilityUrlLive { get { int o = __p.__offset(58); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProbabilityUrlLiveBytes() { return __p.__vector_as_span<byte>(58, 1); }
#else
  public ArraySegment<byte>? GetProbabilityUrlLiveBytes() { return __p.__vector_as_arraysegment(58); }
#endif
  public byte[] GetProbabilityUrlLiveArray() { return __p.__vector_as_array<byte>(58); }
  public FlatDataGlobal.ProductCategory ProductCategory { get { int o = __p.__offset(60); return o != 0 ? (FlatDataGlobal.ProductCategory)__p.bb.GetInt(o + __p.bb_pos) : FlatDataGlobal.ProductCategory.None; } }

  public static Offset<FlatDataGlobal.ShopRecruitExcel> CreateShopRecruitExcel(FlatBufferBuilder builder,
      long Id = 0,
      FlatDataGlobal.ShopCategoryType CategoryType = FlatDataGlobal.ShopCategoryType.General,
      bool IsLegacy = false,
      long OneGachaGoodsId = 0,
      long TenGachaGoodsId = 0,
      StringOffset GoodsDevNameOffset = default(StringOffset),
      FlatDataGlobal.GachaDisplayTag DisplayTag = FlatDataGlobal.GachaDisplayTag.None,
      long DisplayOrder = 0,
      StringOffset GachaBannerPathOffset = default(StringOffset),
      VectorOffset MovieBannerPathOffset = default(VectorOffset),
      VectorOffset MovieBannerPathTeenOffset = default(VectorOffset),
      long LinkedRobbyBannerId = 0,
      VectorOffset InfoCharacterIdOffset = default(VectorOffset),
      StringOffset SalePeriodFromOffset = default(StringOffset),
      StringOffset SalePeriodToOffset = default(StringOffset),
      long RecruitCoinId = 0,
      long RecruitSellectionShopId = 0,
      long PurchaseCooltimeMin = 0,
      long PurchaseCountLimit = 0,
      FlatDataGlobal.PurchaseCountResetType purchaseCountResetType = FlatDataGlobal.PurchaseCountResetType.None,
      bool IsNewbie = false,
      bool IsSelectRecruit = false,
      long DirectPayInvisibleTokenId = 0,
      long DirectPayAndroidShopCashId = 0,
      long DirectPayAppleShopCashId = 0,
      long DirectPayOneStoreShopCashId = 0,
      StringOffset ProbabilityUrlDevOffset = default(StringOffset),
      StringOffset ProbabilityUrlLiveOffset = default(StringOffset),
      FlatDataGlobal.ProductCategory productCategory = FlatDataGlobal.ProductCategory.None) {
    builder.StartTable(29);
    ShopRecruitExcel.AddDirectPayOneStoreShopCashId(builder, DirectPayOneStoreShopCashId);
    ShopRecruitExcel.AddDirectPayAppleShopCashId(builder, DirectPayAppleShopCashId);
    ShopRecruitExcel.AddDirectPayAndroidShopCashId(builder, DirectPayAndroidShopCashId);
    ShopRecruitExcel.AddDirectPayInvisibleTokenId(builder, DirectPayInvisibleTokenId);
    ShopRecruitExcel.AddPurchaseCountLimit(builder, PurchaseCountLimit);
    ShopRecruitExcel.AddPurchaseCooltimeMin(builder, PurchaseCooltimeMin);
    ShopRecruitExcel.AddRecruitSellectionShopId(builder, RecruitSellectionShopId);
    ShopRecruitExcel.AddRecruitCoinId(builder, RecruitCoinId);
    ShopRecruitExcel.AddLinkedRobbyBannerId(builder, LinkedRobbyBannerId);
    ShopRecruitExcel.AddDisplayOrder(builder, DisplayOrder);
    ShopRecruitExcel.AddTenGachaGoodsId(builder, TenGachaGoodsId);
    ShopRecruitExcel.AddOneGachaGoodsId(builder, OneGachaGoodsId);
    ShopRecruitExcel.AddId(builder, Id);
    ShopRecruitExcel.AddProductCategory(builder, productCategory);
    ShopRecruitExcel.AddProbabilityUrlLive(builder, ProbabilityUrlLiveOffset);
    ShopRecruitExcel.AddProbabilityUrlDev(builder, ProbabilityUrlDevOffset);
    ShopRecruitExcel.AddPurchaseCountResetType(builder, purchaseCountResetType);
    ShopRecruitExcel.AddSalePeriodTo(builder, SalePeriodToOffset);
    ShopRecruitExcel.AddSalePeriodFrom(builder, SalePeriodFromOffset);
    ShopRecruitExcel.AddInfoCharacterId(builder, InfoCharacterIdOffset);
    ShopRecruitExcel.AddMovieBannerPathTeen(builder, MovieBannerPathTeenOffset);
    ShopRecruitExcel.AddMovieBannerPath(builder, MovieBannerPathOffset);
    ShopRecruitExcel.AddGachaBannerPath(builder, GachaBannerPathOffset);
    ShopRecruitExcel.AddDisplayTag(builder, DisplayTag);
    ShopRecruitExcel.AddGoodsDevName(builder, GoodsDevNameOffset);
    ShopRecruitExcel.AddCategoryType(builder, CategoryType);
    ShopRecruitExcel.AddIsSelectRecruit(builder, IsSelectRecruit);
    ShopRecruitExcel.AddIsNewbie(builder, IsNewbie);
    ShopRecruitExcel.AddIsLegacy(builder, IsLegacy);
    return ShopRecruitExcel.EndShopRecruitExcel(builder);
  }

  public static void StartShopRecruitExcel(FlatBufferBuilder builder) { builder.StartTable(29); }
  public static void AddId(FlatBufferBuilder builder, long Id) { builder.AddLong(0, Id, 0); }
  public static void AddCategoryType(FlatBufferBuilder builder, FlatDataGlobal.ShopCategoryType CategoryType) { builder.AddInt(1, (int)CategoryType, 0); }
  public static void AddIsLegacy(FlatBufferBuilder builder, bool IsLegacy) { builder.AddBool(2, IsLegacy, false); }
  public static void AddOneGachaGoodsId(FlatBufferBuilder builder, long OneGachaGoodsId) { builder.AddLong(3, OneGachaGoodsId, 0); }
  public static void AddTenGachaGoodsId(FlatBufferBuilder builder, long TenGachaGoodsId) { builder.AddLong(4, TenGachaGoodsId, 0); }
  public static void AddGoodsDevName(FlatBufferBuilder builder, StringOffset GoodsDevNameOffset) { builder.AddOffset(5, GoodsDevNameOffset.Value, 0); }
  public static void AddDisplayTag(FlatBufferBuilder builder, FlatDataGlobal.GachaDisplayTag DisplayTag) { builder.AddInt(6, (int)DisplayTag, 0); }
  public static void AddDisplayOrder(FlatBufferBuilder builder, long DisplayOrder) { builder.AddLong(7, DisplayOrder, 0); }
  public static void AddGachaBannerPath(FlatBufferBuilder builder, StringOffset GachaBannerPathOffset) { builder.AddOffset(8, GachaBannerPathOffset.Value, 0); }
  public static void AddMovieBannerPath(FlatBufferBuilder builder, VectorOffset MovieBannerPathOffset) { builder.AddOffset(9, MovieBannerPathOffset.Value, 0); }
  public static VectorOffset CreateMovieBannerPathVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMovieBannerPathVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMovieBannerPathTeen(FlatBufferBuilder builder, VectorOffset MovieBannerPathTeenOffset) { builder.AddOffset(10, MovieBannerPathTeenOffset.Value, 0); }
  public static VectorOffset CreateMovieBannerPathTeenVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathTeenVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathTeenVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMovieBannerPathTeenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMovieBannerPathTeenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLinkedRobbyBannerId(FlatBufferBuilder builder, long LinkedRobbyBannerId) { builder.AddLong(11, LinkedRobbyBannerId, 0); }
  public static void AddInfoCharacterId(FlatBufferBuilder builder, VectorOffset InfoCharacterIdOffset) { builder.AddOffset(12, InfoCharacterIdOffset.Value, 0); }
  public static VectorOffset CreateInfoCharacterIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInfoCharacterIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInfoCharacterIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInfoCharacterIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInfoCharacterIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddSalePeriodFrom(FlatBufferBuilder builder, StringOffset SalePeriodFromOffset) { builder.AddOffset(13, SalePeriodFromOffset.Value, 0); }
  public static void AddSalePeriodTo(FlatBufferBuilder builder, StringOffset SalePeriodToOffset) { builder.AddOffset(14, SalePeriodToOffset.Value, 0); }
  public static void AddRecruitCoinId(FlatBufferBuilder builder, long RecruitCoinId) { builder.AddLong(15, RecruitCoinId, 0); }
  public static void AddRecruitSellectionShopId(FlatBufferBuilder builder, long RecruitSellectionShopId) { builder.AddLong(16, RecruitSellectionShopId, 0); }
  public static void AddPurchaseCooltimeMin(FlatBufferBuilder builder, long PurchaseCooltimeMin) { builder.AddLong(17, PurchaseCooltimeMin, 0); }
  public static void AddPurchaseCountLimit(FlatBufferBuilder builder, long PurchaseCountLimit) { builder.AddLong(18, PurchaseCountLimit, 0); }
  public static void AddPurchaseCountResetType(FlatBufferBuilder builder, FlatDataGlobal.PurchaseCountResetType purchaseCountResetType) { builder.AddInt(19, (int)purchaseCountResetType, 0); }
  public static void AddIsNewbie(FlatBufferBuilder builder, bool IsNewbie) { builder.AddBool(20, IsNewbie, false); }
  public static void AddIsSelectRecruit(FlatBufferBuilder builder, bool IsSelectRecruit) { builder.AddBool(21, IsSelectRecruit, false); }
  public static void AddDirectPayInvisibleTokenId(FlatBufferBuilder builder, long DirectPayInvisibleTokenId) { builder.AddLong(22, DirectPayInvisibleTokenId, 0); }
  public static void AddDirectPayAndroidShopCashId(FlatBufferBuilder builder, long DirectPayAndroidShopCashId) { builder.AddLong(23, DirectPayAndroidShopCashId, 0); }
  public static void AddDirectPayAppleShopCashId(FlatBufferBuilder builder, long DirectPayAppleShopCashId) { builder.AddLong(24, DirectPayAppleShopCashId, 0); }
  public static void AddDirectPayOneStoreShopCashId(FlatBufferBuilder builder, long DirectPayOneStoreShopCashId) { builder.AddLong(25, DirectPayOneStoreShopCashId, 0); }
  public static void AddProbabilityUrlDev(FlatBufferBuilder builder, StringOffset ProbabilityUrlDevOffset) { builder.AddOffset(26, ProbabilityUrlDevOffset.Value, 0); }
  public static void AddProbabilityUrlLive(FlatBufferBuilder builder, StringOffset ProbabilityUrlLiveOffset) { builder.AddOffset(27, ProbabilityUrlLiveOffset.Value, 0); }
  public static void AddProductCategory(FlatBufferBuilder builder, FlatDataGlobal.ProductCategory productCategory) { builder.AddInt(28, (int)productCategory, 0); }
  public static Offset<FlatDataGlobal.ShopRecruitExcel> EndShopRecruitExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataGlobal.ShopRecruitExcel>(o);
  }
}


}
