// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum StepOpenConditionType : int
{
  None = 0,
  OpenDateOffset = 1,
  ItemAcquire = 2,
};


}
