// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum TacticRange : int
{
  Back = 0,
  Front = 1,
  Middle = 2,
};


}
