// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataGlobal
{

public enum TBGItemType : int
{
  None = 0,
  Dice = 1,
  Heal = 2,
  HealExpansion = 3,
  Defence = 4,
  Guide = 5,
  DiceResultValue = 6,
  DefenceCritical = 7,
};


}
