// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum ArmorType : int
{
  LightArmor = 0,
  HeavyArmor = 1,
  Unarmed = 2,
  Structure = 3,
  Normal = 4,
};


}
