// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum BuffConditionType : int
{
  All = 0,
  Character = 1,
  School = 2,
  Weapon = 3,
};


}
