// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum CurrencyAdditionalChargeType : int
{
  EnableAutoChargeOverLimit = 0,
  DisableAutoChargeOverLimit = 1,
};


}
