// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum CVCollectionType : int
{
  CVNormal = 0,
  CVEvent = 1,
  CVEtc = 2,
};


}
