// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum DamageFontColor : int
{
  Blue = 0,
  White = 1,
  Yellow = 2,
  Red = 3,
  Green = 4,
};


}
