// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum EventNotifyType : int
{
  RewardIncreaseEvent = 0,
  AccountExpIncreaseEvent = 1,
  RaidSeasonManager = 2,
  TimeAttackDungeonSeasonManage = 3,
};


}
