// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MinigameDreamVoiceExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static MinigameDreamVoiceExcel GetRootAsMinigameDreamVoiceExcel(ByteBuffer _bb) { return GetRootAsMinigameDreamVoiceExcel(_bb, new MinigameDreamVoiceExcel()); }
  public static MinigameDreamVoiceExcel GetRootAsMinigameDreamVoiceExcel(ByteBuffer _bb, MinigameDreamVoiceExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MinigameDreamVoiceExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long EventContentId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long UniqueId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatDataJp.DreamMakerVoiceCondition VoiceCondition { get { int o = __p.__offset(8); return o != 0 ? (FlatDataJp.DreamMakerVoiceCondition)__p.bb.GetInt(o + __p.bb_pos) : FlatDataJp.DreamMakerVoiceCondition.None; } }
  public uint VoiceClip { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FlatDataJp.MinigameDreamVoiceExcel> CreateMinigameDreamVoiceExcel(FlatBufferBuilder builder,
      long EventContentId = 0,
      long UniqueId = 0,
      FlatDataJp.DreamMakerVoiceCondition VoiceCondition = FlatDataJp.DreamMakerVoiceCondition.None,
      uint VoiceClip = 0) {
    builder.StartTable(4);
    MinigameDreamVoiceExcel.AddUniqueId(builder, UniqueId);
    MinigameDreamVoiceExcel.AddEventContentId(builder, EventContentId);
    MinigameDreamVoiceExcel.AddVoiceClip(builder, VoiceClip);
    MinigameDreamVoiceExcel.AddVoiceCondition(builder, VoiceCondition);
    return MinigameDreamVoiceExcel.EndMinigameDreamVoiceExcel(builder);
  }

  public static void StartMinigameDreamVoiceExcel(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEventContentId(FlatBufferBuilder builder, long EventContentId) { builder.AddLong(0, EventContentId, 0); }
  public static void AddUniqueId(FlatBufferBuilder builder, long UniqueId) { builder.AddLong(1, UniqueId, 0); }
  public static void AddVoiceCondition(FlatBufferBuilder builder, FlatDataJp.DreamMakerVoiceCondition VoiceCondition) { builder.AddInt(2, (int)VoiceCondition, 0); }
  public static void AddVoiceClip(FlatBufferBuilder builder, uint VoiceClip) { builder.AddUint(3, VoiceClip, 0); }
  public static Offset<FlatDataJp.MinigameDreamVoiceExcel> EndMinigameDreamVoiceExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatDataJp.MinigameDreamVoiceExcel>(o);
  }
}


}
