// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum ReArrangeTargetType : int
{
  AllySelf = 0,
  AllyAll = 1,
  AllyUnitType = 2,
  AllyGroup = 3,
};


}
