// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatDataJp
{

public enum ScenarioCharacterShapes : int
{
  None = 0,
  Signal = 1,
  BlackSilhouette = 2,
  Closeup = 3,
  Highlight = 4,
  WhiteSilhouette = 5,
};


}
